version: 2.1

jobs:
  jdk:
    parameters:
      img:
        type: string
    resource_class: small
    docker:
      - image: << parameters.img >>
    steps:
      - checkout
      - run: whoami
      - run: pwd
      - run:
          name: check git config in curdir exists
          when: always
          command: |
            echo "checking git config on current dir"
            [ -f .config ]
      - run:
          name: check git config in user exists
          when: always
          command: |
            echo "checking git config on ~"
            [ -f ~/.config ]
      - run:
          name: update git config
          command: |
            git config --global core.compression 9
            sudo chmod 755 /home/circleci/.config
          when: always

workflows:
  main:
    jobs:
      - jdk:
          matrix:
            parameters:
              img:
                - cimg/openjdk:11.0.3
                - circleci/openjdk:11.0.3-jdk-stretch
