version: 2.1

commands:
  inspect-gradle:
    steps:
      - run: which gradle
      - run: gradle --version
  install-gradle:
    parameters:
      version:
        type: string
        description: See https://gradle.org/releases/
    steps:
      # see https://github.com/CircleCI-Public/cimg-openjdk/blob/00a075accf7468f5cc6b12687f74f4e8b80bb146/8.0/Dockerfile#L41-L48
      - run: |
          dl_URL="https://services.gradle.org/distributions/gradle-<< parameters.version >>-bin.zip"
          curl -sSL --fail --retry 3 $dl_URL -o gradle.zip
          sudo unzip -d /opt gradle.zip && rm gradle.zip && sudo ln -s /opt/gradle-* /opt/gradle

jobs:
  upgrade-gradle:
    docker:
      - image: cimg/openjdk:8.0-node
    steps:
      - inspect-gradle
      - install-gradle:
          version: "7.6"
      - inspect-gradle

workflows:
  main:
    jobs:
      - upgrade-gradle